@startuml class
title dodgeWall

package unit {
    abstract Unit {
        abstract draw()
    }

    class Ball {
        ballSize
        ballColor
        ballMoveDistance
        ballPoint
        ballName

        Ball(windowHeight, ballName)
        getPoint()
    }

    class Lane {
        lanePoint
        laneColor
        laneBorderColor
        laneBorderWidth
        laneName

        Lane(windowHeight, laneName)
        getPoint()
    }

    class Wall {
        wallHeight
        wallColor
        wallStartPoint
        wallName

        Wall(windowHeight, wallName)
    }

    class Background {
        backgroundColor
        backgroundName

        Backround(windowHeight, backgroundName)
    }
}

package config {
    class WindowConfig {
        height
        width
    }
}

package block {
    class Judge {
        hitJudge(ballPoint, ballSize, wallPoint, wallSpeed)
    }

    class Score {
        setMyHighScore(score)
        getMyHighScore()
    }
}

Ball --|> Unit
Wall --|> Unit
Lane --|> Unit
Background --|> Unit

@enduml